version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/src"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: Asia/Tokyo
    reviewers:
      - "※ レビュワーのGitHubのIDを指定"
    labels:
      - "アップデート対応"
      - "php"
  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: Asia/Tokyo"
    reviewers:
      - "※ レビュワーのGitHubのIDを指定"
    labels:
      - "アップデート対応"
      - "javascript"
