name: test

on:
  push:
    branches:
      - "release"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: docker compose up -d -build

      - name: Test
        run: docker compose exec php-apache-2 /bin/bash
